export const ENTRIES_REQUESTED = "entries/ENTRIES_REQUESTED";
export const ENTRIES_REQUESTED_FULFILLED =
  "entries/ENTRIES_REQUESTED_FULFILLED";
export const ENTRIES_REQUESTED_REJECTED = "entries/ENTRIES_REQUESTED_REJECTED";
export const ENTRIES_SET_FILTER = "entries/ENTRIES_SET_FILTER";
